[buildPlans.IosevkaTermSs12]
family = "IosevkaTermSS12"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaTermSs12.variants]
  inherits = "ss12"

    [buildPlans.IosevkaTermSs12.variants.design]
    one = "no-base"
    two = "straight-neck-serifless"
    four = "closed-serifless"
    five = "oblique-flat-serifless"
    nine = "straight-bar"
    zero = "oval-slashed"
    capital-a = "curly-serifless"
    capital-d = "standard-serifless"
    capital-g = "toothed-serifless-hooked"
    capital-k = "curly-serifless"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-p = "closed-serifless"
    capital-u = "toothless-rounded-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "straight-serifless-with-crossbar"
    a = "double-storey-tailed"
    c = "serifless"
    d = "tailed-serifless"
    e = "rounded"
    f = "flat-hook-serifless"
    g = "double-storey-open"
    h = "tailed-serifless"
    i = "tailed-serifed"
    j = "flat-hook-serifed"
    k = "cursive-serifless"
    l = "tailed-serifed"
    m = "tailed-serifless"
    n = "tailed-motion-serifed"
    p = "eared-serifless"
    q = "diagonal-tailed-serifless"
    r = "corner-hooked-top-serifed"
    s = "serifless"
    t = "bent-hook-short-neck"
    u = "tailed-serifless"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "semi-chancery-curly-serifless"
    y = "straight-turn-serifless"
    z = "curly-serifless"
    ampersand = "closed"
    at = "fourfold-tall"
    bar = "natural-slope"
    lig-equal-chain = "without-notch"

  [buildPlans.IosevkaTermSs12.ligations]
  inherits = "dlig"

[buildPlans.IosevkaTermSs12.weights.Regular]
shape = 400
menu = 400
css = 400
